---
title: "H587 Project 1"
author: "Peter Banwarth"
date: "9/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code
```{r}

library(readxl)
library(table1)

# read in data
burn <- read_excel("BurnData.xlsx")

# relabeling field values
burn$newtrt <- factor(burn$newtrt,levels = c(0,1),
                      labels = c("Standard Treatment","New Treatment"))

burn$status <- factor(burn$status, levels = c(0,1),
                      labels = c("Discharged without infection","Infection"))

burn$female <-   factor(burn$female, levels=c(0,1),
                        labels=c("Male","Female"))

burn$white <- factor(burn$white,levels = c(0,1),
                     labels = c("Does not identify as White","Identifies as White"))

burn$burntype <- factor(burn$burntype,levels = c(1:4),
                        labels <- c("Chemical","Scald","Electric","Flame"))

units(burn$saburned) <- "percent"

# labeling fields
labels <- list(
  variables=list(newtrt="Treatment",
                 status="Status",
                 female="Sex",
                 white="Race",
                 burntype = "Burn type",
                 saburned = "Surface area burned (percent)")
  )

strata <- c(list(Total=burn),split(burn,burn$newtrt))
```

## Output
```{r}
#table1(strata,labels) # original output

df<-as.data.frame(table1(strata,labels)) #change from html table to dataframe
df[rbind(c(3,3),c(3,4),c(4,3),c(4,4))]<-NA # Set NA's # Set NAs
df <- df[-c(2,5,8,11,14,19),] # Remove header rows
rownames(df)<-c() #Remove numbered rownames

#Recreate table
library(kableExtra)
kable(df) %>% 
  kable_classic(html_font = "Arial") %>% #set look and font
  row_spec(0,bold=T) %>%  #bold header
  row_spec(1,bold=T, hline_after=TRUE) %>%  #bold header
  #set Sub headers
  group_rows(group_label = "Treatment", start_row = 2, end_row = 3) %>%  
  group_rows(group_label = "Status", start_row = 4, end_row = 5) %>% 
  group_rows(group_label = "Sex", start_row = 6, end_row = 7) %>% 
  group_rows(group_label = "Race", start_row = 8, end_row = 9) %>% 
  group_rows(group_label = "Burn type", start_row = 10, end_row = 13) %>% 
  group_rows(group_label = "Surface area burned (percent)", start_row = 14, end_row = 15)
```


### Resources used in this assignment:

https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html

https://bookdown.org/yihui/rmarkdown/basics.html

https://rmarkdown.rstudio.com/lesson-9.html
